# labeling_script.py

import pandas as pd
from datetime import datetime, timedelta
import os # Added for path operations

# This script depends on the classes defined in your other files
from data_handler import DataHandler
from analysis_engine import AnalysisEngine

class DataLabeler:
    """
    Uses the AnalysisEngine to programmatically label a feature dataset
    based on identified Elliott Wave patterns.
    """
    def __init__(self, ticker: str, feature_file_path: str):
        """
        Initializes the labeler.

        Args:
            ticker (str): The stock ticker symbol.
            feature_file_path (str): The path to the CSV file generated by feature_generator.py.
        """
        if not os.path.exists(feature_file_path):
            raise FileNotFoundError(f"Feature file not found at: {feature_file_path}")

        self.ticker = ticker
        self.feature_df = pd.read_csv(feature_file_path, index_col='Date', parse_dates=True)

        # Ensure the index is timezone-aware if the fetched data is.
        # This helps in consistent date/time operations.
        if self.feature_df.index.tz is None:
            # Assuming 'Asia/Kolkata' if not specified, based on yfinance output seen before
            self.feature_df.index = self.feature_df.index.tz_localize('Asia/Kolkata')

        self.handler = DataHandler(ticker)
        # Fetch a long period of data for a comprehensive analysis.
        # Ensure price_data also becomes timezone-aware for consistent comparison with feature_df.
        start_date = self.feature_df.index.min() - timedelta(days=100) # Add buffer
        self.price_data = self.handler.fetch_historical_data(start_date=start_date.strftime('%Y-%m-%d'))

        if self.price_data.index.tz is None:
             self.price_data.index = self.price_data.index.tz_localize('Asia/Kolkata')


        print("DataLabeler initialized.")

    def label_dataset(self):
        """
        Runs the analysis engine and assigns labels to the feature dataset.
        Returns the labeled DataFrame.
        """
        print("Running full historical analysis to find all wave patterns for labeling...")

        # Initialize the analysis engine with the full price history
        analyzer = AnalysisEngine(data_df=self.price_data)

        # We use settings here optimized for finding patterns in daily data for labeling
        analyzer.find_swing_points(order=20)
        # Use the flexible find_elliott_wave_impulse method to find all valid patterns
        analyzer.find_elliott_wave_impulse(buffer=0.05) # Using a 5% buffer

        print(f"Found {len(analyzer.elliott_waves)} patterns with flexible rules. Now applying labels...")

        # Start by labeling everything as '0' (No Clear Pattern)
        self.feature_df['label'] = 0

        # Define what each number means for our labels
        label_map = {
            'wave_1': 1, 'wave_2': 2, 'wave_3': 3, 'wave_4': 4, 'wave_5': 5,
            'wave_a': 6, 'wave_b': 7, 'wave_c': 8
        }

        # Iterate through each pattern the analyzer found
        for wave in analyzer.elliott_waves:
            points = wave['points']
            # Label the impulse waves 1-5
            for i in range(5):
                # Ensure start/end dates are timezone-aware for loc
                start_date = points.index[i]
                end_date = points.index[i+1]
                wave_number_label = label_map[f'wave_{i+1}']

                # Use .loc with timezone-aware indices directly
                self.feature_df.loc[start_date:end_date, 'label'] = wave_number_label

            # Label the projected A-B-C correction
            # NOTE: This part relies on analyzer.abc_projection being populated,
            # which is currently not implemented in AnalysisEngine.
            # If you implement project_abc_correction in AnalysisEngine,
            # ensure it populates analyzer.abc_projection with datetime objects.
            proj = analyzer.abc_projection
            if proj and 'p5' in proj and 'A' in proj and 'B' in proj and 'C' in proj:
                p5_date, a_date, b_date, c_date = proj['p5'][0], proj['A'][0], proj['B'][0], proj['C'][0]
                self.feature_df.loc[p5_date:a_date, 'label'] = label_map['wave_a']
                self.feature_df.loc[a_date:b_date, 'label'] = label_map['wave_b']
                self.feature_df.loc[b_date:c_date, 'label'] = label_map['wave_c']

        print("Labeling complete.")
        return self.feature_df

# --- NEW FUNCTION FOR ORCHESTRATION ---
def run_labeling_pipeline(ticker: str, feature_file_path: str, output_dir: str = '.'):
    """
    Orchestrates data labeling for a given ticker.
    It loads the feature data, applies labels, and saves the labeled dataset to a CSV.
    Returns True on success, False otherwise.
    """
    print(f"\n--- Running Data Labeling for {ticker} ---")
    try:
        labeler = DataLabeler(ticker=ticker, feature_file_path=feature_file_path)
        labeled_df = labeler.label_dataset()
        output_filename = os.path.join(output_dir, f"{ticker}_labeled_dataset.csv")
        labeled_df.to_csv(output_filename, index=True)
        print(f"Successfully created labeled dataset and saved to '{output_filename}'.")

        print("\n--- Label Distribution Summary ---")
        print("0=NoPattern, 1-5=ImpulseWaves, 6-8=CorrectiveWaves")
        print(labeled_df['label'].value_counts().sort_index())
        return True
    except FileNotFoundError as e:
        print(f"ERROR: {e}")
        return False
    except Exception as e:
        print(f"--- ERROR ---: An error occurred during labeling: {e}")
        return False

# This block allows you to run the script directly from your terminal
if __name__ == '__main__':
    stock_ticker = 'RELIANCE.NS'
    # Define a default path, assuming feature_generator.py has been run
    feature_filename = f"{stock_ticker}_features.csv"

    print(f"\n--- Creating labeled dataset for {stock_ticker} ---")
    run_labeling_pipeline(stock_ticker, feature_filename) # Calls the new function for direct execution
