# labeling_script.py

import pandas as pd
import numpy as np
import os

class DataLabeler:
    """
    Labels a feature dataset based on the actual future price movement.
    This approach is objective and replaces the subjective Elliott Wave analysis.
    """
    def __init__(self, feature_file_path: str):
        """
        Initializes the labeler.

        Args:
            feature_file_path (str): Path to the CSV file generated by feature_generator.py.
        """
        if not os.path.exists(feature_file_path):
            raise FileNotFoundError(f"Feature file not found at: {feature_file_path}")
        
        # Load the dataset with features already generated.
        # The 'Date' column is loaded as the index.
        self.feature_df = pd.read_csv(feature_file_path, index_col='Date', parse_dates=True)
        print("DataLabeler initialized with feature dataset.")

    def add_future_trend_labels(self, forecast_days: int = 5, up_threshold: float = 1.5, down_threshold: float = -1.5):
        """
        Calculates the future price change and assigns a label.

        Args:
            forecast_days (int): The number of trading days to look into the future.
            up_threshold (float): The percentage increase required to be labeled an UPTREND.
            down_threshold (float): The percentage decrease required to be labeled a DOWNTREND.
        """
        print(f"Generating labels based on price change over the next {forecast_days} trading days...")
        
        # Use pandas' shift() method to get the closing price N days in the future.
        # A negative shift brings future values to the present row.
        future_close = self.feature_df['Close'].shift(-forecast_days)
        
        # Calculate the percentage change from the current close to the future close
        self.feature_df['future_pct_change'] = ((future_close - self.feature_df['Close']) / self.feature_df['Close']) * 100

        # Define the labeling function based on thresholds
        def apply_label(pct_change):
            if pct_change > up_threshold:
                return 1  # UPTREND
            elif pct_change < down_threshold:
                return 2  # DOWNTREND
            else:
                return 0  # SIDEWAYS

        # Apply the function to create the 'label' column.
        # This will have NaNs for the last 'forecast_days' rows, which is expected.
        self.feature_df['label'] = self.feature_df['future_pct_change'].apply(apply_label)
        
        # Remove rows where a label could not be calculated (the last few days of the dataset)
        self.feature_df.dropna(subset=['label', 'future_pct_change'], inplace=True)
        
        # Convert label to integer type
        self.feature_df['label'] = self.feature_df['label'].astype(int)

        print("Labeling complete.")
        return self.feature_df

def run_labeling_pipeline(ticker: str, feature_file_path: str, output_dir: str = '.'):
    """
    Orchestrates data labeling and saves the labeled dataset to a CSV.
    """
    print(f"\n--- Running Data Labeling for {ticker} ---")
    try:
        labeler = DataLabeler(feature_file_path=feature_file_path)
        labeled_df = labeler.add_future_trend_labels()
        
        output_filename = os.path.join(output_dir, f"{ticker}_labeled_dataset.csv")
        labeled_df.to_csv(output_filename, index=True)
        print(f"Successfully created labeled dataset and saved to '{output_filename}'.")

        print("\n--- Label Distribution Summary ---")
        print("0=SIDEWAYS, 1=UPTREND, 2=DOWNTREND")
        print(labeled_df['label'].value_counts(normalize=True).sort_index())
        return True
    except FileNotFoundError as e:
        print(f"ERROR: {e}")
        return False
    except Exception as e:
        print(f"--- ERROR ---: An error occurred during labeling: {e}")
        return False

# This block allows you to run the script directly from your terminal for testing
if __name__ == '__main__':
    stock_ticker = 'RELIANCE.NS'
    output_directory = 'training_dataset'
    # The feature file is expected to be in the training_dataset directory
    feature_filename = os.path.join(output_directory, f"{stock_ticker}_features.csv")

    print(f"\n--- Creating labeled dataset for {stock_ticker} ---")
    # First, ensure the feature file exists by running the feature generator
    from feature_generator import run_feature_generation_pipeline
    if not os.path.exists(feature_filename):
        run_feature_generation_pipeline(stock_ticker, output_dir=output_directory)
    
    # Now run the labeling pipeline
    run_labeling_pipeline(stock_ticker, feature_filename, output_dir=output_directory)
